// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: login_events.sql

package db

import (
	"context"
	"database/sql"
)

const insertLoginEvent = `-- name: InsertLoginEvent :exec
INSERT INTO login_events (
    user_id,
    username,
    success,
    reason,
    ip,
    user_agent
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6
)
`

type InsertLoginEventParams struct {
	UserID    interface{}    `json:"user_id"`
	Username  sql.NullString `json:"username"`
	Success   bool           `json:"success"`
	Reason    sql.NullString `json:"reason"`
	Ip        sql.NullString `json:"ip"`
	UserAgent sql.NullString `json:"user_agent"`
}

func (q *Queries) InsertLoginEvent(ctx context.Context, arg InsertLoginEventParams) error {
	_, err := q.db.ExecContext(ctx, insertLoginEvent,
		arg.UserID,
		arg.Username,
		arg.Success,
		arg.Reason,
		arg.Ip,
		arg.UserAgent,
	)
	return err
}
