// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type LoginEvent struct {
	ID        int64          `json:"id"`
	UserID    interface{}    `json:"user_id"`
	Username  sql.NullString `json:"username"`
	Success   bool           `json:"success"`
	Reason    sql.NullString `json:"reason"`
	Ip        sql.NullString `json:"ip"`
	UserAgent sql.NullString `json:"user_agent"`
	CreatedAt time.Time      `json:"created_at"`
}

type Session struct {
	ID        string         `json:"id"`
	UserID    int64          `json:"user_id"`
	CreatedAt time.Time      `json:"created_at"`
	ExpiresAt time.Time      `json:"expires_at"`
	RevokedAt sql.NullTime   `json:"revoked_at"`
	RevokedBy sql.NullString `json:"revoked_by"`
}

type User struct {
	ID           int64     `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	IsBanned     bool      `json:"is_banned"`
}
