// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (
    id,
    user_id,
    created_at,
    expires_at,
    revoked_at,
    revoked_by
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    NULL,
    NULL
)
`

type CreateSessionParams struct {
	ID        string    `json:"id"`
	UserID    int64     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = CURRENT_TIMESTAMP,
    revoked_by = ?2
WHERE id = ?1
  AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	ID        string         `json:"id"`
	RevokedBy sql.NullString `json:"revoked_by"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.ExecContext(ctx, revokeSession, arg.ID, arg.RevokedBy)
	return err
}
